### ISSUE TITLE
Problema al traer historical market data

### ISSUE THREAD

**Issue by matinoseda** [itAtPPI/ppi-connector-python#3]
Hola, quiero traerme el precio del spot y del futuro de GGAL.
Ejecuto lo siguiente:

`data_accion= ppi.marketdata.search("GGAL", "acciones", "A-48HS", datetime(2022, 4, 16), dt.date.today())`
`print(prueba_acc)`
`data_futuro = ppi.marketdata.search("GGAL/AGO22", "FUTUROS", "A-24HS", datetime(2022, 4, 16), dt.date.today())`
`print(prueba_acc)`

Y me devuelve la misma market data: 

```
[{'date': '2022-06-14T00:00:00-03:00', 'price': 899.5, 'volume': 79853136, 'openingPrice': 917, 'max': 933, 'min': 890.05}, {'date': '2022-06-15T00:00:00-03:00', 'price': 894.4, 'volume': 151320576, 'openingPrice': 905, 'max': 920, 'min': 875}, {'date': '2022-06-16T00:00:00-03:00', 'price': 870.55, 'volume': 180845859.45, 'openingPrice': 876, 'max': 880.35, 'min': 863}]

[{'date': '2022-06-14T00:00:00-03:00', 'price': 899.5, 'volume': 79853136, 'openingPrice': 917, 'max': 933, 'min': 890.05}, {'date': '2022-06-15T00:00:00-03:00', 'price': 894.4, 'volume': 151320576, 'openingPrice': 905, 'max': 920, 'min': 875}, {'date': '2022-06-16T00:00:00-03:00', 'price': 870.55, 'volume': 180845859.45, 'openingPrice': 876, 'max': 880.35, 'min': 863}]
```

Puede ser que al llamar precios históricos de futuros me traiga el realidad precios del spot? O estoy llamando mal a la función?

**Comment by marceloferrer** [comment]
Buen dia, puede ser que ambos print tengan el nombre de la variable de la misma variable? Fijate que en ambos casos haces:
print(prueba_acc).

Tal vez el codigo deberia quedarte asi?

data_accion= ppi.marketdata.search("GGAL", "acciones", "A-48HS", datetime(2022, 4, 16), dt.date.today())
print(data_accion)
data_futuro = ppi.marketdata.search("GGAL/AGO22", "FUTUROS", "A-24HS", datetime(2022, 4, 16), dt.date.today())
print(data_futuro)

**Comment by matinoseda** [comment]
Era eso mismo, gracias
